apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoflask
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echoflask
  template:
    metadata:
      labels:
        name: echoflask
    spec:
      serviceAccountName: echoflask
      containers:
        - name: echoflask
          # Replace this with the built image name
          image: takeyan/echoflask-operator:0.0.1
          command:
          - echoflask
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "echoflask"
